### ISSUE TITLE
Error: Cannot find module 'param-case'

### ISSUE THREAD

**Issue by caotrem** [skovy/typed-scss-modules#14]
After installing by entering `npm install typed-scss-modules -D` and running by entering `.\node_modules\.bin\tsm --help` or `npx tsm --help` I get the following error stack trace
```
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'param-case'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Caotrem\Development\Demo 04\node_modules\typed-scss-modules\dist\lib\sass\file-to-class-names.js:8:36)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

**Comment by caotrem** [comment]
Just found out that the npm packages `param-case` and `reserved-words` do not get installed as a dependency. A manual install `npm install param-case -D` and `npm install reserved-words -D` is working as a work around in the moment.

**Comment by skovy** [comment]
Thanks for reporting @caotrem! https://github.com/skovy/typed-scss-modules/pull/15 should resolve this issue and changes can be picked up in this release: https://www.npmjs.com/package/typed-scss-modules/v/0.0.8

**Comment by caotrem** [comment]
Thx for the fast fix @skovy
