### ISSUE TITLE
Upgrade from 7.1.4 to 8.0.0 breaks on scss single-line comments

### ISSUE THREAD

**Issue by kubijo** [skovy/typed-scss-modules#221]
## Expected Behavior

Valid SCSS file should not produce any errors

## Current Behavior

```
CssSyntaxError: /xxx/conf/storybook/styles/layout.scss:30:1: Unexpected '/'. Escaping special characters with \ may help.
    at /xxx/conf/storybook/styles/layout.scss:30:1
    at Input.error (/xxx/.yarn/cache/postcss-npm-8.4.34-2179f0d4b5-ff4769ff69.zip/node_modules/postcss/lib/input.js:106:16)
    at Rule.error (/xxx/.yarn/cache/postcss-npm-8.4.34-2179f0d4b5-ff4769ff69.zip/node_modules/postcss/lib/node.js:115:32)
    at Root._error (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:132:25)
    at Root.error (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/selectors/root.js:30:19)
    at Parser.error (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:596:21)
    at Parser.unexpected (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:610:17)
    at Parser.combinator (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:525:12)
    at Parser.parse (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:897:14)
    at Parser.loop (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:853:12)
    at new Parser (/xxx/.yarn/cache/postcss-selector-parser-npm-6.0.15-0ec4819b4e-cea591e1d9.zip/node_modules/postcss-selector-parser/dist/parser.js:123:10) {
  reason: "Unexpected '/'. Escaping special characters with \\ may help.",
  file: '/xxx/conf/storybook/styles/layout.scss',
```

## Your Environment

- Version used: `8.0.0`
- Operating System and versions:
  - yarn: `4.0.2`
  - node: `v20.5.0`
  - system: `Ubuntu 23.10`

**Comment by kubijo** [comment]
@gmathieu @skovy Any chance for a fix guys?
