### ISSUE TITLE
Using the composes from "filepath" breaks TSM

### ISSUE THREAD

**Issue by OfriHarlev** [skovy/typed-scss-modules#57]
When I have two files 

foo.module.scss
`
.foo {
width: 50px;
}
`
bar.module.scss
`
.bar {
  composes: foo from "./foo.module.scss";
}
`
I get the following error when I run TSM and it attempts to process the composes keyword.

`(node:55481) UnhandledPromiseRejectionWarning: TypeError: this.pathFetcher is not a function
    at Parser.fetchImport (/Users/ofri/s0/node_modules/css-modules-loader-core/lib/parser.js:90:19)
    at /Users/ofri/s0/node_modules/css-modules-loader-core/lib/parser.js:49:31
    at Root.each (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/container.js:110:22)
    at Parser.fetchAllImports (/Users/ofri/s0/node_modules/css-modules-loader-core/lib/parser.js:47:11)
    at Parser.plugin (/Users/ofri/s0/node_modules/css-modules-loader-core/lib/parser.js:35:31)
    at LazyResult.run (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:197:22)
    at LazyResult.asyncTick (/Users/ofri/s0/node_modules/css-modules-loader-core/node_modules/postcss/lib/lazy-result.js:197:22)
(node:55481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:55481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by OfriHarlev** [comment]
I now think this has nothing to do with composes and instead only something to do with file paths. When I do the same thing with 
bar.module.scss
`
@values foo foo from "./foo.module.scss";
`
I get the same issue

**Comment by skovy** [comment]
@OfriHarlev is this valid SASS Syntax or does this require additional processors/loaders/plugins? Would you mind linking me to the related docs on https://sass-lang.com? Thanks!

**Comment by OfriHarlev** [comment]
I didn't find it in sass-lang but look at the composition header here https://github.com/css-modules/css-modules

**Comment by skovy** [comment]
Ah, I see. I believe this would require additional loaders/processors to handle this syntax since this is using the standard SASS packages. This would likely be a lot of work because we would need to entirely redo the way the processing works. I'm happy to entertain the idea if you'd like to propose a potential solution and implementation!

**Comment by skovy** [comment]
Closing this issue since it's stale and this functionality is not built into SASS itself so would be a pretty significant departure from the current implementation.
